baseURL = 'https://destcom-student-projects.github.io/hugo-course/'
languageCode = 'fr-FR'
title = 'Cours récapitulatif de HUGO & GH Pages'
theme = "PaperMod"

[params.custom]
logoName = "HUGO & Github Pages"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowBreadCrumbs = true
env = "production"
description = "Micro récapitulatif d'un cours de HUGO"
author = "DestCom"
ShowShareButtons = true

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"

[params.homeInfoParams]
Title = "Cours récapitulatif de HUGO & GH Pages"
Content = "Retrouvez ici un court résumé de l'introduction a HUGO et Github Pages"

[params.analytics.google]
SiteVerificationTag = "zJ0i7OiRkxZG7S8VwurKRWZpzS-UHbf-PR1HJ7peb_Y"

[[params.socialIcons]]
name = "github"
url = "https://github.com/DestroyCom"

[[params.socialIcons]]
name = "other"
url = "https://portfolio.stroyco.eu/"

[[params.socialIcons]]
name = "youtube"
url = "https://stroygetter.stroyco.eu/"

[[menu.main]]
identfier = "search"
name = "Search"
url = "/search/"

[[menu.main]]
identfier = "posts"
name = "All the posts"
url = "/posts/"

[[menu.main]]
identfier = "home"
name = "Home"
url = "/"

[[params.custom.externalSites]]
name = "Portfolio"
url = "https://portfolio.stroyco.eu/"

[[params.custom.externalSites]]
name = "StroyGetter"
url = "https://stroygetter.stroyco.eu/"